### ISSUE TITLE
Possibly unnecessary `if` clause? or incomplete implementation 

### ISSUE THREAD

**Issue by yawboakye** [ftechspace/learning_rust#1]
what does this method do? it seems to be evaluating the same expression in both hands of the if clause https://github.com/ftechspace/learning_rust/blob/46d17bfe4cfcb672f1e77c2bf669cab41ee060dc/src/chapter_5_structs.rs#L17

**Comment by ftechspace** [comment]
> what does this method do? it seems to be evaluating the same expression in both hands of the if clause
> 
> https://github.com/ftechspace/learning_rust/blob/46d17bfe4cfcb672f1e77c2bf669cab41ee060dc/src/chapter_5_structs.rs#L17

Yes, it is true it's unnecessary but the goal was to practice passing values into a `fn` in an `impl`
like this `let check_width = rectangle.check_dimension_value(width_string);`

The `if` clause isn't the main focus

**Comment by yawboakye** [comment]
got it!
